README.md, ballerina.conf, googlespreadsheet4/Ballerina.md, googlespreadsheet4/google_spreadsheet_connector.bal, googlespreadsheet4/google_spreadsheet_structs.bal, tests/test.bal
=> Add documentation

gsheets/google_spreadsheet_connector.bal, gsheets/google_spreadsheet_endpoint.bal, gsheets/google_spreadsheet_objects.bal, gsheets/google_spreadsheet_transformers.bal, gsheets/test/Ballerina.md, gsheets/test/test.bal
=> Add minor changes and doc annotations

README.md, gsheets/Package.md, gsheets/google_spreadsheet_connector.bal, gsheets/test/Ballerina.md
=> Add changes to support Ballerina Alpha4 version

gsheets/google_spreadsheet_connector.bal
=> Add fix to retrieve all values from a sheet

README.md, gsheets/Package.md, gsheets/google_spreadsheet_connector.bal, gsheets/google_spreadsheet_endpoint.bal, gsheets/google_spreadsheet_objects.bal, gsheets/test/Ballerina.md, gsheets/test/test.bal
=> Add new http client changes

README.md, gsheets4/Package.md, gsheets4/gsheets_connector.bal, gsheets4/gsheets_data_mappings.bal, gsheets4/gsheets_endpoint.bal, gsheets4/gsheets_types.bal, gsheets4/test/Ballerina.md, gsheets4/test/test.bal
=> Fix review changes

.gitignore, Ballerina.toml, README.md, gsheets4/Package.md, gsheets4/gsheets_connector.bal, gsheets4/gsheets_constants.bal, gsheets4/gsheets_endpoint.bal, gsheets4/gsheets_types.bal, gsheets4/test/Ballerina.md, gsheets4/test/test.bal
=> Add fix to support beta3

Ballerina.toml, README.md, gsheets4/Package.md, gsheets4/gsheets_connector.bal, gsheets4/test/Ballerina.md
=> Adding Beta10 syntax changes.

Ballerina.toml, README.md, gsheets4/Package.md, gsheets4/gsheets_connector.bal, gsheets4/test/Ballerina.md
=> Add doc changes

Ballerina.toml, gsheets4/Package.md, gsheets4/gsheets_connector.bal, gsheets4/gsheets_data_mappings.bal, gsheets4/gsheets_endpoint.bal, gsheets4/test/test.bal
=> Reformat the code

gsheets4/Package.md
=> Minor change in package.md

gsheets4/gsheets_connector.bal, gsheets4/gsheets_constants.bal, gsheets4/gsheets_data_mappings.bal, gsheets4/gsheets_types.bal, gsheets4/test/test.bal
=> Add more methods

README.md, gsheets4/Package.md, gsheets4/gsheets_connector.bal, gsheets4/gsheets_endpoint.bal, gsheets4/test/Ballerina.md
=> Add changes to support ballerina 0.974.1

Ballerina.toml, README.md, gsheets4/Package.md, gsheets4/gsheets_connector.bal, gsheets4/gsheets_endpoint.bal, gsheets4/test/Ballerina.md, gsheets4/test/test.bal
=> Fix for Ballerina 0.975.0 changes

README.md, gsheets4/Package.md
=> Update markdown files

gsheets4/gsheets_connector.bal, gsheets4/gsheets_endpoint.bal, gsheets4/gsheets_types.bal
This PR fixes some syntax issues in the package.
=> Fix syntax issues

Ballerina.toml, README.md, gsheets4/Package.md, gsheets4/test/Ballerina.md
Update markdown files and toml file for 0.980.0 release
=> Prepare connector for Ballerina 0.980.0 release

.travis.yml, Ballerina.toml, README.md, gsheets4/Package.md, gsheets4/tests/Ballerina.md
> Update Google Spreadsheet connector for 0.981.0 stable release
=> Update for 0.981.0 release

Ballerina.toml, README.md, gsheets4/Package.md, gsheets4/gsheets_connector.bal, gsheets4/gsheets_endpoint.bal, gsheets4/gsheets_types.bal, gsheets4/tests/Ballerina.md
Fix connector with latest ballerina changes.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Fix connector with latest ballerina changes

Ballerina.toml
Change connector version.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Change connector version

Ballerina.toml, README.md, gsheets4/Module.md, gsheets4/tests/Ballerina.md, gsheets4/tests/test.bal
Sync with ballerina 0.983.0
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Sync with ballerina 0.983.0

Ballerina.toml, README.md, gsheets4/Module.md
- Fix markdown and update toml version
=> Release for Ballerina 0.990.0 RC3

Ballerina.toml, README.md, gsheets4/Module.md, gsheets4/gsheets_endpoint.bal, gsheets4/gsheets_types.bal, gsheets4/tests/Ballerina.md
=> Fix connector for Ballerina 0.990.3

Ballerina.toml, README.md, gsheets4/Module.md
=> Fix code samples in the README.md

.travis.yml, Ballerina.toml, README.md, gsheets4/Module.md, gsheets4/gsheets_constants.bal, gsheets4/gsheets_endpoint.bal, gsheets4/gsheets_types.bal, gsheets4/tests/Ballerina.md, gsheets4/tests/test.bal
Update the connector with ballerina-0.991.0
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Sync with ballerina-0.991.0

src/gsheets4/tests/test.bal
> Migrated to Ballerina alpha 3 version.
=> Migrated to Ballerina alpha 3 version

Ballerina.lock, README.md, src/gsheets4/Module.md, src/gsheets4/gsheets_endpoint.bal, src/gsheets4/tests/test.bal
The issue had with default truststore after removing `ballerina.home` fixed by checking the custom truststore passed by the client. Otherwise, initialize the unsecured connection with the server.
`SpreadsheetConfiguration` with secure socket config
```
gsheets4:SpreadsheetConfiguration spreadsheetConfig = {
oAuthClientConfig: {
accessToken: "<accessToken>",
refreshConfig: {
clientId: "<clientId>",
clientSecret: "<clientSecret>",
refreshUrl: "<refreshUrl>",
refreshToken: "<refreshToken>",
clientConfig: {
secureSocket:{
trustStore:{
path: "<fullQualifiedPathToTrustStore>",
password: "<truststorePassword>"
}
}
}
}
},
secureSocketConfig: …
```
=> Initialize unsecured connection if the client doesn't provide secure socket config

src/gsheets4/gsheets_types.bal, src/gsheets4/gsheets_utils.bal, src/gsheets4/tests/Ballerina.md, src/gsheets4/tests/test.bal
`ballerina/internal` module no longer exists. Therefore, I wrote a util function for equalsIgnoreCase. Then replace it with existing usage.
> Brief description of the new feature or bug fix as it will appear in the …
=> Fix compilation issue with latest RC1 and verified tests are passing

.travis.yml, Ballerina.lock, Ballerina.toml, README.md, src/gsheets4/Module.md, src/gsheets4/gsheets_endpoint.bal, src/gsheets4/tests/test.bal
In the previous RC release doesn't have a way to get the default truststore. Hence, we disable to secure socket if the client doesn't provide the custom truststore. The latest release fixed that issue by providing default java keystore. Therefore, remove the code disable secure socket.
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too …
=> Remove disable secure socket with the fix of latest RC release

Ballerina.lock, Ballerina.toml
Bump connector version from `0.8.25` to `0.9.0`
> Link(s) to product documentation that addresses the changes of this PR. If no …
=> Bump connector version

src/gsheets4/gsheets_constants.bal
Access modifier to set public in the REFRESH_URL constant since it's already used by ballerina guides.
> Link(s) to product …
=> Set access modifier to public in REFRESH_URL

.travis.yml
Update the Travis configurations. 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Modify .travis.yaml file

src/gsheets4/Module.md
Modify module.md file to include the sample code and testing of the sample
=> Modify module.md file to include the sample code and testing

.github/workflows/ci.yml
=> Add CI git action

.github/workflows/ci.yml, .github/workflows/release.yml
=> Update git actions

src/gsheets4/tests/test.bal, src/gsheets4/types.bal
=> Check build failure 

src/gsheets4/tests/test.bal
=> Add minor code refactoring

.github/workflows/ci.yml
=> Update CI git action

src/gsheets4/client.bal, src/gsheets4/constants.bal, src/gsheets4/tests/test.bal
=> Add functionality open spreadsheet by url

src/gsheets4/Module.md, src/gsheets4/client.bal, src/gsheets4/data_mappings.bal, src/gsheets4/sheet.bal, src/gsheets4/spreadsheet.bal, src/gsheets4/tests/test.bal, src/gsheets4/utils.bal
=> Add changed from code review

src/gsheets4/tests/test.bal
=> Fix test failure

src/gsheets4/constants.bal, src/gsheets4/sheet.bal, src/gsheets4/tests/test.bal
=> Fix test failures

.github/workflows/ci.yml, .github/workflows/release.yml, src/gsheets4/constants.bal, src/gsheets4/sheet.bal, src/gsheets4/tests/test.bal
=> Fix test failures 

.travis.yml, Ballerina.lock, Ballerina.toml, README.md, src/googleapis.sheets4/Module.md, src/googleapis.sheets4/client.bal, src/googleapis.sheets4/constants.bal, src/googleapis.sheets4/data_mappings.bal, src/googleapis.sheets4/sheet.bal, src/googleapis.sheets4/spreadsheet.bal, src/googleapis.sheets4/tests/test.bal, src/googleapis.sheets4/utils.bal
=> Migrate to Ballerina Swan Lake Preview1

metadata/google_sheet.json
> To add display name for UI needs.
> Make available user friendly display names.
=> Added Remaining metada for UI

Ballerina.toml, Module.md, client.bal, constants.bal, data_mappings.bal, tests/test.bal, types.bal
=> Add get all Spreadsheets functionality

Ballerina.toml, client.bal, constants.bal, metadata/google_sheet.json, tests/test.bal, types.bal, utils.bal
=> Add streaming for getting all spreadsheets

gradle.properties
> Update appropriate ballerinaLangVersion in gradle.properties file.
> Use correct ballerinaLangVersion in gradle build.
=> Update Ballerina Lang version for gradle build

gsheet/Ballerina.toml
> The current implementation doesn't use the exact java wrapper version to build the ballerina project. Modify the exact version.
> Update the exact java wrapper version to build the ballerina project.
=> Update java-wrapper version

gsheet/client.bal, gsheet/modules/listener/tests/test.bal, gsheet/modules/listener/types.bal, gsheet/stream_implementer.bal, gsheet/types.bal, gsheet/utils.bal
> 
Display annotations for some operations are long. We need to follow the new structure given: 
https://docs.google.com/document/d/1-jUPEM8AzagPs-LZKY6g8mQFtqHirWcjxOA0gn6r-f4/edit?usp=sharing
Resolves https://github.com/wso2-enterprise/choreo/issues/4558
Non remote function getIdFromUrl is displayed as an remote operation in choreo. This should be removed.
Resolves https://github.com/wso2-enterprise/choreo/issues/4556
Change http response type as `http:Response' since 'var' is used earlier. Improve listener test logic.
> 
Improve the display annotations following the new structure guidelines
Improve user experience in Choreo by fixing relevant issues to the connector
> 
Fix http response type
Improve listener test logic
Move `getIdFromUrl` function to utils.bal
Improve the display …
=> Improve display annotations & fix choreo issues

gradle.properties, gsheet/Ballerina.toml, gsheet/client.bal, gsheet/tests/test.bal
> The display annotations for Google Sheets connector is inconsistent
> $Subject
=> [SL Alpha 5] Make display annotations for Google Sheets connector consistant

gsheet/client.bal, gsheet/tests/test.bal
> The display annotations for Google Sheets connector is inconsistent
> $Subject
=> [SL Beta 1] Make display annotations for Google Sheets connector consistant

gradle.properties, gsheet/Ballerina.toml
> Bump version to 0.99.11
> Bump version to 0.99.11
=> Bump version to 0.99.11

gradle.properties, gsheet/Dependencies.toml, gsheet/resources/File_data.json, gsheet/resources/Range_data.json, gsheet/resources/SheetProperties_data.json, gsheet/resources/Sheet_data.json, gsheet/resources/SpreadsheetProperties_data.json, gsheet/resources/Spreadsheet_data.json
> Bump dependency versions to beta2
=> Bump versions to beta2

gsheet/Package.md
> $Subject
> Update documentation
> 
JDK 11
Ballerina Beta 2
Ubuntu 20.04
=> [SL Beta 2] Update documentation

gsheet/Package.md
> $Subject
> Update documentation
> 
JDK 11
Ballerina Beta 2
Ubuntu 20.04
=> [Master] Update documentation

README.md, gsheet/Dependencies.toml, gsheet/Package.md
- Bump version to slbeta3 in Dependencies.toml, README.md and Package.md
JDK 11
Ballerina SLBeta3-SNAPSHOT
=> Bump versions for slbeta3 in master branch

gradle.properties, gsheet/Dependencies.toml, gsheet/client.bal, gsheet/samples/getAllSpreadsheets.bal, gsheet/tests/test.bal
- Bump dependency versions
- Fix stream related breaking change, test cases and sample
JDK 11
Ballerina SLBeta3
=> Migrate to slbeta3

.github/workflows/ci.yml, .github/workflows/daily-build.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, README.md, gsheet/Dependencies.toml
Related https://github.com/ballerina-platform/ballerina-extended-library/issues/128
- Add slbeta4 migration changes
* Ballerina Version: Ballerina swan lake beta 4
* Operating System: Ubuntu (Linux)
* Java SDK: Java 11
=> Add beta4 migration changes

README.md, gradle.properties, gsheet/Ballerina.toml, gsheet/Dependencies.toml, gsheet/Package.md
- Bump version to `2.1.0`
- Update Ballerina version to `SLBeta6` in Package.md 
- Regenerate Dependencies.toml with `SLBeta6`
- Add `distribution = "slbeta6"` in Ballerina.toml
=> Prepare for 2.1.0 release with SLBeta6

gsheet/Dependencies.toml
- Update Dependencies.toml with latest standard library versions
=> Update Dependencies.toml with latest standard library versions

gradle.properties, gsheet/Ballerina.toml, gsheet/Dependencies.toml, gsheet/Package.md
- Prepare for 2.2.0 release with ballerina 2201.0.0
=> Prepare for 2.2.0 release with ballerina 2201.0.0

gsheet/client.bal
Improve API doc for input parameters `valueInputOption` and `valueRenderOption`.
Resolves https://github.com/ballerina-platform/ballerina-extended-library/issues/440
- Improve API doc for input parameters `valueInputOption` and `valueRenderOption`.
* Ballerina Version: 2201.0.3
* Operating System: 20.04
* Java SDK: 11
=> Improve API doc for input parameters `valueInputOption` and `valueRenderOption`

.github/workflows/dev-stg-release.yml, .github/workflows/release.yml, gsheet/Ballerina.toml, gsheet/Dependencies.toml, gsheet/Package.md
Update package for release v3.0.1
- Update package for release v3.0.1
* Ballerina Version: 2201.1.0
* Operating System: Ubuntu 20.04
* Java SDK: 11
=> Update package for release v3.0.1

.github/workflows/dev-stg-release.yml, .github/workflows/release.yml, gsheet/Ballerina.toml, gsheet/Dependencies.toml, gsheet/Package.md, gsheet/client.bal, gsheet/config-types.bal
- Alter ConnectionConfig record 
- Bump connector version and ballerina version in Ballerina.toml
- Bump ballerina version in Package.md
- Update Dependencies.toml with Ballerina 2201.2.0
=> Alter ConnectionConfig record

gsheet/client.bal, gsheet/config-types.bal
- Remove `clientConfig` from `OAuth2RefreshTokenGrantConfig`
=> Remove `clientConfig` from `OAuth2RefreshTokenGrantConfig` record

.github/workflows/dev-stg-release.yml, .github/workflows/release.yml, gsheet/Ballerina.toml, gsheet/Package.md
=> Bump bal version to 2201.2.1

gsheet/Ballerina.toml, gsheet/Dependencies.toml, gsheet/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/475
=> Update to Ballerina version 2201.3.0

gsheet/client.bal
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Pull request 1
- Pull request 2
* Java SDK:
=> Update doc comments on APIs

gsheet/client.bal, gsheet/tests/test.bal, gsheet/types.bal
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Pull request 1
- Pull request 2
* Java SDK:
=> Fix commented issues and update tests

gsheet/Ballerina.toml
$subject
- Pull request 1
- Pull request 2
* Java SDK:
=> Update google sheets connector version to 3.3.0

gsheet/types.bal
Update faulty doc comment
- Pull request 1
- Pull request 2
* Java SDK:
=> Update doc comments for the value range

gsheet/client.bal
$subject
- [267](https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/pull/267)
* Java SDK:
=> Update client with requested changes

gsheet/client.bal, gsheet/tests/test.bal, gsheet/types.bal, gsheet/utils.bal
$subject
- [267](https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/pull/267)
* Java SDK:
=> Update code according to the comments

gsheet/client.bal, gsheet/tests/test.bal, gsheet/types.bal
$subject
- [267](https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/pull/267)
* Java SDK:
=> Update Code according to comments

.github/workflows/ci.yml, .github/workflows/daily-build.yml, .github/workflows/pull-request.yml, README.md
$title
Related to [#533](https://github.com/ballerina-platform/ballerina-extended-library/issues/533)
=>  Integrate codecov with github actions #278 

ballerina/Dependencies.toml, ballerina/utils.bal
=> Remove usages of regex module

README.md
=> Fix file name error in GraalVM check

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/Module.md, gradle.properties
Fixes: [#6947](https://github.com/ballerina-platform/ballerina-library/issues/6947)
N/A
=> [2201.8.x] Fix Broken Links in Module.md

.github/workflows/build-with-bal-test-graalvm.yml, .github/workflows/ci.yml, .github/workflows/daily-build.yml, .github/workflows/dev-stage-release.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, .github/workflows/trivy-scan.yml
=> [2201.8.x] Update Central Publish Workflows

.github/workflows/build-with-bal-test-graalvm.yml, .github/workflows/ci.yml, .github/workflows/daily-build.yml, .github/workflows/dev-stage-release.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, .github/workflows/trivy-scan.yml, docs/spec/spec.md
=> Update Release Workflows

.gitignore
=> Update gitignore File
